url: 
sitename: 'Jekyll Starter'
description: 'A base Jekyll theme'
# do not include  https://github.com/...
#Pages - store all pages in the _pages directory

include: ['_pages']
exclude: ['readme.md','license.md','Gemfile', 'CNAME', 'bower.json', 'node_modules', 'bower_components', 'sass', 'gulpfile.js', 'package.json']

# Build settings
markdown: kramdown
permalink: pretty
# dev options (true/false)
# if site is in production, 'production: true'
production: false
bust_css_cache: true


# options (data)
google_analytics_id: UA-xxxx
disqus_id:
addthis_id:

# CONTACT FORM http://getsimpleform.com/
simple_form_api_token:
directory_assets_img: /assets/img/

# options (social)
# facebook_id:
twitter_id: budparr

sass:
    style: :compressed
    sass_dir: assets/css/_sass

collections:
  books:
    output: true
    permalink: /book/:path/
    layout: page
  reviews:
    output: false

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"

